name: build test & upload pypi

on:
  push:
    branches: ["release"]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        make init
        make install
    - name: Build package & publish
      run: |
        make wheel
        make release
      env:
        user: sorrychoe
        password: ${{ secrets.PYPI_PASSWORD }}
