name: build test & upload pypi

on:
  push:
    branches: ["release"]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        make init
        make install
    - name: Build wheel
      run: |
        make wheel
    - name: Publish to Pypi
      run: |
          python3 -m pip install twine

          python3 -m twine upload dist/*.whl --non-interactive -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
